import manifest from "@/assets/generated/photo.json" with { type: "json" };

const src = (format: "avif" | "webp" | "jpg", size: "160" | "320") => manifest[format][size];

/** Responsive sources for the portrait <picture>, generated by scripts/images.mjs. */
export const photoSources = {
  avif160: src("avif", "160"),
  avif: `${src("avif", "160")} 1x, ${src("avif", "320")} 2x`,
  webp: `${src("webp", "160")} 1x, ${src("webp", "320")} 2x`,
  jpg: {
    src: src("jpg", "160"),
    srcSet: `${src("jpg", "160")} 1x, ${src("jpg", "320")} 2x`,
    width: 160,
    height: 160,
  },
};
