import avif160 from "@/assets/generated/photo-160.avif";
import jpg160 from "@/assets/generated/photo-160.jpg";
import webp160 from "@/assets/generated/photo-160.webp";
import avif320 from "@/assets/generated/photo-320.avif";
import jpg320 from "@/assets/generated/photo-320.jpg";
import webp320 from "@/assets/generated/photo-320.webp";

/** Responsive sources for the portrait <picture>, generated by scripts/images.mjs. */
export const photoSources = {
  avif: `${avif160.src} 1x, ${avif320.src} 2x`,
  webp: `${webp160.src} 1x, ${webp320.src} 2x`,
  jpg: { src: jpg160.src, srcSet: `${jpg160.src} 1x, ${jpg320.src} 2x`, width: 160, height: 160 },
};
