// GENERATED by tools/gen.py — do not edit by hand. Run: pnpm gen
export const cvHtml = `
<img class="bg" src="__BG__" alt="">
<img class="photo" src="__PHOTO__" alt="Portretfoto van Jens Penneman">
<div class="t" style="left:177.6pt;top:43.26pt;font-weight:400;font-size:6.96pt;line-height:1.165em;color:#595959">Teerlingstraat 69/2, 9190 Stekene, België&nbsp;&nbsp;-&nbsp;&nbsp;<a href="mailto:jenspenneman26@gmail.com">jenspenneman26@gmail.com</a>&nbsp;&nbsp;-&nbsp;&nbsp;<a href="tel:+32474180683">+32 474 18 06 83</a></div>
<h1 class="t" style="left:177.50pt;top:67.66pt;font-weight:700;font-size:18.96pt;line-height:1.192em;color:#000000">Jens Penneman, Software engineer</h1>
<p class="t intro" style="left:177.6pt;top:96.15pt;width:381.7pt;font-weight:400;font-size:12pt;line-height:1.43333em;color:#3F3F3F">Full-stack software engineer met 4 jaar ervaring. Ik bouw dashboards, klantenportalen en koppelingen met externe diensten, van database tot pixel-perfecte interface.</p>
<h2 class="t" style="left:35.90pt;top:198.37pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Personalia</h2>
<div class="t" style="left:177.60pt;top:198.47pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Nationaliteit</div>
<div class="t" style="right:234.52pt;top:198.26pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">Belg</div>
<div class="hl" style="left:232.26pt;top:206.44pt;width:102.21pt"></div>
<div class="t" style="left:369.60pt;top:198.47pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Rijbewijs</div>
<div class="t" style="right:36.00pt;top:198.26pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">AM, B</div>
<div class="hl" style="left:412.25pt;top:206.44pt;width:114.40pt"></div>
<div class="t" style="left:177.60pt;top:219.37pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Geboorteplaats</div>
<div class="t" style="right:234.52pt;top:219.16pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">Sint-Niklaas</div>
<div class="hl" style="left:246.93pt;top:227.34pt;width:54.89pt"></div>
<div class="t" style="left:369.60pt;top:219.37pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Geboortedatum</div>
<div class="t" style="right:36.00pt;top:219.16pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">23/11/2002</div>
<div class="hl" style="left:440.28pt;top:227.34pt;width:65.33pt"></div>
<h2 class="t" style="left:35.90pt;top:261.37pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Werkervaring</h2>
<h3 class="t" style="left:177.60pt;top:261.18pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Full stack software engineer</h3>
<div class="t" style="left:177.60pt;top:278.57pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij Advantitge te Deinze, Juli 2025 - heden</div>
<h3 class="t" style="left:177.60pt;top:300.68pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Full stack software engineer</h3>
<div class="t" style="left:177.60pt;top:318.07pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij Lemon Companies te Kontich, Juli 2024 - Mei 2025</div>
<h3 class="t" style="left:177.60pt;top:340.18pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Student-zelfstandige</h3>
<div class="t" style="left:177.60pt;top:357.57pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij WEB4YOU te Stekene, Oktober 2021 - Juni 2024</div>
<h3 class="t" style="left:177.60pt;top:379.68pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Stagiair front end engineer</h3>
<div class="t" style="left:177.60pt;top:397.07pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij BASF te Gent, Oktober 2023 - December 2023</div>
<div class="t" style="left:177.60pt;top:418.86pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">+ 5 vakantiejobs</div>
<div class="t" style="left:177.60pt;top:432.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij Bpost, Storaenso, Houtshop Van der Gucht, V3 Consulting… 2017 - 2022</div>
<h2 class="t" style="left:35.90pt;top:474.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Vaardigheden</h2>
<div class="t" style="left:177.60pt;top:474.77pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Frontend</div>
<div class="t" style="right:36.00pt;top:474.56pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">React, NextJS, TypeScript, Tailwind, TanStack Query</div>
<div class="hl" style="left:220.94pt;top:482.74pt;width:104.70pt"></div>
<div class="t" style="left:177.60pt;top:495.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Backend</div>
<div class="t" style="right:36.00pt;top:495.46pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">NodeJS, GraphQL, Hasura, REST, PostgreSQL, Strapi</div>
<div class="hl" style="left:220.28pt;top:503.64pt;width:102.99pt"></div>
<div class="t" style="left:177.60pt;top:516.57pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Cloud en tooling</div>
<div class="t" style="right:36.00pt;top:516.36pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">AWS, Vercel, Supabase, Sentry, Git, pnpm, Turborepo</div>
<div class="hl" style="left:250.78pt;top:524.54pt;width:72.03pt"></div>
<h2 class="t" style="left:35.90pt;top:558.57pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Opleidingen</h2>
<h3 class="t" style="left:177.60pt;top:558.28pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Toegepaste informatica</h3>
<div class="t" style="left:177.60pt;top:575.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij Hogeschool Gent, September 2020 - December 2023</div>
<h3 class="t" style="left:177.60pt;top:596.28pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Industriële informatica &amp; communicatietechnieken</h3>
<div class="t" style="left:177.60pt;top:613.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij GTI Beveren, September 2018 - Juli 2020</div>
<h3 class="t" style="left:177.60pt;top:634.28pt;font-weight:700;font-size:12.0pt;line-height:1.192em;color:#000000">Elektromechanica</h3>
<div class="t" style="left:177.60pt;top:651.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">bij Broederschool Stekene, September 2016 - Juli 2018</div>
<h2 class="t" style="left:35.90pt;top:693.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Cursussen (geattesteerd)</h2>
<div class="t" style="left:177.60pt;top:693.47pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">Instructeur</div>
<div class="t" style="left:227.97pt;top:693.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">(2024) en</div>
<div class="t" style="left:268.19pt;top:693.47pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">Hoofdanimator</div>
<div class="t" style="left:335.86pt;top:693.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">(2022) bij KLJ en de Vlaamse Overheid</div>
<h2 class="t" style="left:35.90pt;top:735.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Talen</h2>
<div class="t" style="left:177.60pt;top:736.37pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Moedertaal</div>
<div class="t" style="right:234.52pt;top:736.16pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">Nederlands</div>
<div class="hl" style="left:230.10pt;top:744.34pt;width:74.54pt"></div>
<div class="t" style="left:369.60pt;top:736.37pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Zeer goed</div>
<div class="t" style="right:36.00pt;top:736.16pt;font-weight:700;font-size:9.0pt;line-height:1.192em;color:#000000">Engels</div>
<div class="hl" style="left:417.77pt;top:744.34pt;width:105.56pt"></div>
<h2 class="t" style="left:35.90pt;top:777.67pt;font-weight:400;font-size:9.0pt;line-height:1.165em;color:#7F7F7F">Andere informatiekanalen</h2>
<div class="t" style="left:177.70pt;top:778.76pt;font-weight:400;font-size:6.96pt;line-height:1.165em;color:#595959"><a href="https://jenspenneman.com/">https://jenspenneman.com/</a></div>
<div class="t" style="left:177.70pt;top:787.16pt;font-weight:400;font-size:6.96pt;line-height:1.165em;color:#595959"><a href="https://linkedin.com/in/jenspenneman/">https://linkedin.com/in/jenspenneman/</a></div>
<div class="t" style="left:372.20pt;top:778.76pt;font-weight:400;font-size:6.96pt;line-height:1.165em;color:#595959"><a href="https://github.com/JensPenneman">https://github.com/JensPenneman</a></div>
`;
